---
steps:
  - label: Build and test CDK App
    command: echo Hello World!
    agents:
      queue: default
  - label: Run Docker Build
    agents:
      queue: kubernetes
    plugins:
      - docker-compose#v5.3.0:
          build: cdk
          config: .buildkite/docker-compose.ci.yml
      - kubernetes:
          gitEnvFrom:
            - secretRef:
                name: ssh-credentials
