steps:
  - name: ":docker: Build"
    label: Run Docker Build
    key: docker-build
    agents:
      queue: kubernetes
    plugins:
    - docker-compose#v5.3.0:
        build: cdk
        config: .buildkite/docker-compose.ci.yml
