---
steps:
  - label: hello
    key: hello
    command: echo "Hello, world!"
    agents:
      queue: kubernetes
    plugins:
  - label: Run Docker Build
    key: docker-build
    agents:
      queue: kubernetes
    plugins:
      - docker-compose#v5.3.0:
          build: cdk
          config: .buildkite/docker-compose.ci.yml
