---
steps:
  - label: Build and test CDK App
    command: echo Hello World!
    agents:
      queue: default
  - label: Run Docker Build
    agents:
      queue: kubernetes
    plugins:
      - docker#v5.11.0:
        image: "golang:1.21"
      - kubernetes:
          gitEnvFrom:
            - secretRef:
                name: ssh-credentials
